USE metro_cdmx;

ALTER TABLE `stations`
	MODIFY `updated_at` TIMESTAMP NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `lines_stations`
	MODIFY `updated_at` TIMESTAMP NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `locations`
	MODIFY `updated_at` TIMESTAMP NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `trains`
	MODIFY `updated_at` TIMESTAMP NOT NULL 
    DEFAULT CURRENT_TIMESTAMP 
    ON UPDATE CURRENT_TIMESTAMP;